---
title: "Tarea 3"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r carga-paquetes, include=FALSE}
library(dplyr)
library(sf)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
library(readxl)
library(lubridate)
library(stringi)
```

```{r}
cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r}
delitos_oij <-
  readxl::read_excel("estadisticaspoliciales2021.xls")
```

```{r}
delitos_oij$Fecha <- as.Date(delitos_oij$Fecha, format("%d/%m/%Y"))
```

Column {data-width=550}
-----------------------------------------------------------------------

### Mapa

```{r}
cantones <- 
  cantones %>%
  mutate(canton_normalizado = tolower(stri_trans_general(canton, id = "Latin-ASCII")))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  mutate(Canton = if_else(Canton == "LEON CORTES", "LEON CORTES CASTRO", Canton)) %>%
  mutate(Canton = if_else(Canton == "VASQUEZ DE CORONADO", "VAZQUEZ DE CORONADO", Canton))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  left_join(
    dplyr::select(
      st_drop_geometry(cantones),
      cod_canton,
      canton_normalizado
    ),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r}
delitos_x_canton <-
  delitos_oij %>%
  count(cod_canton, name = "delitos")
```

```{r}
cantones_delitos <-
  cantones %>%
  left_join(
    delitos_x_canton,
    by = "cod_canton",
    copy = FALSE,
    keep = FALSE
  )
```

```{r}
colores_cantones_delitos <-
  colorNumeric(
    palette = "Reds",
    domain = cantones_delitos$delitos,
    na.color = "transparent"
  )
```

```{r}
leaflet() %>%
  setView(lng = -84.19452,
          lat = 9.572735,
          zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(
    data = cantones_delitos,
    fillColor = ~ colores_cantones_delitos(cantones_delitos$delitos),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste("<strong>Cantón:</strong>",
            cantones_delitos$canton),
      paste("<strong>Delitos:</strong>",
            cantones_delitos$delitos),
      sep = "<br/>"
    ),
    group = "Delitos en cantones"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en cantones")
  ) %>%
  addLegend(
    position = "bottomleft",
    pal = colores_cantones_delitos,
    values = cantones_delitos$delitos,
    group = "Delitos",
    title = "Cantidad de delitos"
  )
```

### Tabla

```{r}
delitos_oij <-
  delitos_oij %>%
  dplyr::select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton)
```

```{r}
delitos_oij %>%
  datatable(colnames = c("Delito", "Fecha", "Víctima", "Edad", "Género", "Provincia", "Cantón"),
    options = list(
    pageLenght = 10,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```

### Gráfico 1

```{r grafico-delitos, message=FALSE, echo=FALSE}
grafico_delitos <-
  delitos_oij %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por cada delito") +
  xlab("Delito") +
  ylab("Cantidad de delitos") +
  coord_flip() +
  theme_minimal()
```

```{r lectura-grafico-delitos, message=FALSE, echo=FALSE}
ggplotly(grafico_delitos) %>% config(locale = "es")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Gráfico 2

```{r grafico-victimas, message=FALSE, echo=FALSE}
grafico_victima <-
  delitos_oij %>%
  count(Victima) %>%
  ggplot(aes(x = reorder(Victima, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por víctima") +
  xlab("Víctima") +
  ylab("Cantidad de delitos") +
  theme_classic()
```

```{r lectura-grafico-victimas, message=FALSE, echo=FALSE}
ggplotly(grafico_victima) %>% config(locale = "es")
```

### Gráfico 3

```{r datos-meses, message=FALSE, echo=FALSE}
meses_delitos <-
  delitos_oij %>%
  mutate(Meses = lubridate::month(Fecha, label = TRUE))
```

```{r grafico-delitos-mes, message=FALSE, echo=FALSE}
grafico_delitos_mes <-
  meses_delitos %>%
  count(Meses) %>%
  ggplot(aes(x = Meses, y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Mes") +
  ylab("Cantidad de delitos") +
  theme_minimal()
```

```{r lectura-grafico-delitos-mes, message=FALSE, echo=FALSE}
ggplotly(grafico_delitos_mes) %>% config(locale = "es")
```

### Gráfico 4

```{r grafico-apilado-genero, message=FALSE, echo=FALSE}
grafico_apilado_genero <-
  delitos_oij %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Proporción de delitos por género") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Género") +
  coord_flip() +
  theme_minimal ()
```

```{r}
ggplotly(grafico_apilado_genero) %>% config(locale = "es")
```

